# Generated by Django 5.1.4 on 2025-01-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topapps',
            name='webpage',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
