# Generated by Django 5.1.4 on 2025-01-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstore', '0002_topapps_webpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topapps',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topapps',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='topapps',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
